#!/usr/bin/env python3
"""
GraphifyStenoMD Weekly Report Workflow
Generates weekly summary report.

Usage:
    python3 workflows/weekly_report.py       # Show preview
    python3 workflows/weekly_report.py --save   # Save report
"""

import json
import sys
from datetime import datetime, timedelta
from pathlib import Path

# Add project scripts to path for centralized config
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "scripts"))

try:
    from config import get_config
    config = get_config()
    PROJECT_DIR = config.PROJECT_ROOT
    VAULT_DIR = config.VAULT_DIR
    KG_DIR = config.KG_DIR
    ENTITIES_FILE = config.ENTITIES_FILE
except ImportError:
    PROJECT_DIR = Path("/home/adrian/Desktop/NEDAILAB/StenoMD")
    VAULT_DIR = PROJECT_DIR / "vault"
    KG_DIR = PROJECT_DIR / "knowledge_graph"
    ENTITIES_FILE = KG_DIR / "entities.json"

GRAPH_FILE = PROJECT_DIR / "Graphify" / "graphify-out" / "graph.json"
OUTPUT_DIR = PROJECT_DIR / "GraphifyStenoMD" / "reports"

def load_graph():
    """Load graph data."""
    if GRAPH_FILE.exists():
        with open(GRAPH_FILE) as f:
            return json.load(f)
    return {"nodes": [], "links": []}

def count_by_type(graph):
    """Count entities by type."""
    counts = {"politicians": 0, "sessions": 0, "laws": 0}
    for node in graph.get("nodes", []):
        source = node.get("source_file", "")
        if "politicians/" in source or "senators/" in source or "deputies/" in source:
            counts["politicians"] += 1
        elif "sessions/" in source:
            counts["sessions"] += 1
        elif "laws/" in source:
            counts["laws"] += 1
    return counts

def weekly_report():
    """Generate weekly report."""
    graph = load_graph()
    counts = count_by_type(graph)
    
    report = []
    report.append(f"# Weekly Report - {datetime.now().strftime('%Y-%m-%d')}")
    report.append("")
    report.append("## Summary")
    report.append("")
    report.append(f"- Graph nodes: {len(graph.get('nodes', []))}")
    report.append(f"- Graph edges: {len(graph.get('links', []))}")
    report.append(f"- Politicians: {counts['politicians']}")
    report.append(f"- Sessions: {counts['sessions']}")
    report.append(f"- Laws: {counts['laws']}")
    report.append("")
    report.append("---\n")
    report.append("*Generated by GraphifyStenoMD*")
    
    return "\n".join(report)

def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--save", action="store_true", help="Save report")
    args = parser.parse_args()
    
    content = weekly_report()
    print(content)
    
    if args.save:
        OUTPUT_DIR.mkdir(exist_ok=True)
        filename = f"weekly_{datetime.now().strftime('%Y%m%d')}.md"
        (OUTPUT_DIR / filename).write_text(content)
        print(f"\nSaved: {OUTPUT_DIR / filename}")

if __name__ == "__main__":
    main()