#!/usr/bin/env python3
"""
Ruflo Orchestration Bridge for StenoMD

Provides a function to generate Ruflo config and run the swarm.
If Ruflo is not installed or fails, returns a non-zero exit code.
Intended to be called from the daily pipeline when STENOMD_USE_RUFLO=true.
"""

import os
import subprocess
import sys
from pathlib import Path


RUFLO_CONFIG_TEMPLATE = """
# StenoMD workflow generated by ruflo_bridge.py
name: StenoMD Daily Pipeline
description: Orchestrated by Ruflo

agents:
  scraper_cdep:
    type: command
    command: python3
    args: ["scripts/agents/cdep_agent.py", "--years", "2024,2025,2026", "--max-id", "50", "--sync-vault"]
    workdir: .
    timeout: 1800

  scraper_senat:
    type: command
    command: python3
    args: ["scripts/agents/senat_agent.py", "--year", "2026", "--max", "30", "--sync-vault"]
    workdir: .
    timeout: 1800

  enricher:
    type: command
    command: python3
    args: ["scripts/fix_deputy_data_from_op.py"]
    workdir: .
    timeout: 600

  committees:
    type: command
    command: python3
    args: ["scripts/add_committees.py"]
    workdir: .
    timeout: 600

  merge_kg:
    type: command
    command: python3
    args: ["scripts/merge_vault_to_kg.py"]
    workdir: .
    timeout: 300

workflow:
  - scraper_cdep
  - scraper_senat
  - enricher
  - committees
  - merge_kg
"""


def generate_ruflo_config(output_path: Path) -> None:
    """Write Ruflo config YAML."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(RUFLO_CONFIG_TEMPLATE.strip() + "\n")
    print(f"[RufloBridge] Generated config: {output_path}")


def run_ruflo_swarm(config_path: Path) -> int:
    """Run ruflo swarm. Returns exit code."""
    cmd = ["ruflo", "swarm", "--config", str(config_path)]
    print(f"[RufloBridge] Running: {' '.join(cmd)}")
    try:
        result = subprocess.run(cmd, check=False)
        return result.returncode
    except FileNotFoundError:
        print("[RufloBridge] 'ruflo' command not found in PATH.")
        return 1


def run_pipeline(dry_run: bool = False) -> int:
    """Generate config and run Ruflo (dry_run not supported by Ruflo)."""
    # dry-run is ignored; Ruflo itself doesn't have dry-run
    ruflo_cfg_dir = Path(os.environ.get('STENOMD_RUFLO_CONFIG_DIR', '.ruflo'))
    ruflo_cfg_path = ruflo_cfg_dir / 'stenomd_pipeline.yaml'
    try:
        generate_ruflo_config(ruflo_cfg_path)
        return run_ruflo_swarm(ruflo_cfg_path)
    except Exception as e:
        print(f"[RufloBridge] Error: {e}")
        return 1
